In [1]:
import warnings; warnings.simplefilter('ignore')
from dcr import *

In [3]:
%matplotlib inline
plt.rcParams['figure.dpi'] = 300
plt.rcParams['figure.figsize'] = (16, 9)
plt.rcParams.update({'font.size': 16})

In [4]:
data, data_train, data_test, X_train_scaled, X_test_scaled, y_train, y_test = dataprep(data)

In [5]:
data

,id,time,orig_time,first_time,mat_time,res_time,balance_time,LTV_time,interest_rate_time,rate_time,...,age_1f,age2,vintage,vintage2,PCA1_1,PCA2_1,PCA3_1,PCA4_1,PCA5_1,cluster_1
0,4.0,25.0,-2.0,25.0,119.0,NaN,61031.10,33.911009,10.500,5.90,...,1.0,1.0,0.0,0.0,-0.104556,0.523194,-0.232270,-0.506923,0.062275,1.0
1,9.0,25.0,18.0,25.0,138.0,NaN,127156.28,65.642484,8.730,4.14,...,1.0,1.0,18.0,324.0,-0.104556,0.523194,-0.232270,-0.506923,0.062275,1.0
2,47.0,25.0,19.0,25.0,139.0,NaN,130286.14,66.793811,6.930,4.24,...,1.0,1.0,19.0,361.0,-0.104556,0.523194,-0.232270,-0.506923,0.062275,1.0
3,13.0,25.0,18.0,25.0,138.0,NaN,228957.49,65.211476,7.560,4.14,...,1.0,1.0,18.0,324.0,-0.104556,0.523194,-0.232270,-0.506923,0.062275,1.0
4,35.0,25.0,19.0,25.0,139.0,NaN,78586.07,66.810457,7.030,4.24,...,1.0,1.0,19.0,361.0,-0.104556,0.523194,-0.232270,-0.506923,0.062275,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58996,37843.0,15.0,13.0,15.0,73.0,NaN,44042.18,62.876322,5.125,3.54,...,1.0,1.0,13.0,169.0,-0.723759,-0.138599,0.118036,-0.559650,-0.405142,1.0
58997,38271.0,15.0,9.0,12.0,129.0,NaN,638742.73,57.759641,5.750,4.86,...,3.0,16.0,9.0,81.0,-0.723759,-0.138599,0.118036,-0.559650,-0.405142,1.0
58998,38752.0,15.0,11.0,15.0,131.0,NaN,333958.30,65.428152,6.000,3.83,...,1.0,1.0,11.0,121.0,-0.723759,-0.138599,0.118036,-0.559650,-0.405142,1.0
58999,39221.0,15.0,8.0,12.0,128.0,NaN,471428.67,43.327570,6.250,5.42,...,3.0,16.0,8.0,64.0,-0.723759,-0.138599,0.118036,-0.559650,-0.405142,1.0
59000,40487.0,15.0,-4.0,2.0,56.0,NaN,56148.46,40.446417,10.500,5.25,...,13.0,196.0,0.0,0.0,-0.723759,-0.138599,0.118036,-0.559650,-0.405142,1.0